import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sean Hale Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
		  <section id="hero" className="h-screen flex flex-col justify-between">
			  <section className="flex flex-col items-center justify-center space-y-2 mt-64 mx-4 mx-4">
				  <h1 className="text-5xl">Sean Hale</h1>
				  <div className="w-3/4 md:w-1/2 h-1 bg-gradient-to-r from-pink-500 via-yellow-300 to-purple-600" />
				  <section className="flex flex-row justify-center items-stretch space-x-4">
				  <Link href="https://git.deers.io/west">GitLab</Link>
				  <Link href="https://github.com/sean-hale-dev">GitHub</Link>
				  <Link href="https://www.linkedin.com/in/sean-h-39a99412a/">LinkedIn</Link>
				  <Link href="https://git.deers.io/west/resume/-/raw/main/resume.pdf">Resume</Link>
				  <Link href="/">Photo Portfolio</Link>
				  </section>

				  <div className="">
					  <a href="#code-portfolio">
						  <button className="m-4 p-2 rounded">Code Portfolio</button>
					  </a>
				  </div>
			  </section>

			  <div className={styles.spacer} id={styles['hero-spacer']} />
		  </section>

		  <section id="Proficiencies" className="bg-purple-600 h-screen">
			  <h2 className="text-3xl lg:text-5xl text-white">Proficiencies</h2>
		  </section>

		  <section id="code-portfolio" className="bg-pink-500 h-screen">
			  <h2 className="text-3xl lg:text-5xl text-white">Code Portfolio</h2>
		  </section>

      </main>
    </>
  );
};

export default Home;
